AllCops:
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'vendor/**/*'
    - 'old_main.rb'
    - 'old_main2.rb'

# 日本語コメントぐらい使わせてくれ
Style/AsciiComments:
  Enabled: false

# 流石に1関数に10行は少ない。
# ついでにコメントもカウントしないでくれ
Metrics/MethodLength:
  CountComments: false
  Max: 20